const data = [
  {
    company: "Photosnap",
    tag: ["New!", "Featured"],
    job: "Senior Frontend Developer",
    post: "1d ago",
    type: "Full Time",
    location: "USA only",
    role: "Frontend",
    level: "Senior",
    language: ["HTML", "CSS", "JavaScript"],
    tools: [],
    filters: ["Frontend", "Senior", "HTML", "CSS", "JavaScript"]
  },
  {
    company: "Manage",
    tag: ["New!", "Featured"],
    job: "Fullstack Developer",
    post: "1d ago",
    type: "Part Time",
    location: "Remote",
    role: "Fullstack",
    level: "Midweight",
    language: ["Python"],
    tools: ["React"],
    filters: ["Fullstack", "Midweight", "Python", "React"]
  },
  {
    company: "Account",
    tag: ["New!"],
    job: "Junior Frontend Developer",
    post: "2d ago",
    type: "Part Time",
    location: "USA only",
    role: "Frontend",
    level: "Junior",
    language: ["JavaScript"],
    tools: ["React", "Sass"],
    filters: ["Frontend", "Junior", "JavaScript", "React", "Sass"]

  },
  {
    company: "MyHome",
    tag: [],
    job: "Junior Frontend Developer",
    post: "5d ago",
    type: "Contract",
    location: "USA only",
    role: "Frontend",
    level: "Junior",
    language: ["CSS", "JavaScript"],
    tools: [],
    filters: ["Frontend", "Junior", "CSS", "JavaScript"]
  },
  {
    company: "Loop Studios",
    tag: [],
    job: "Software Engineer",
    post: "1w ago",
    type: "Full Time",
    location: "Worldwide",
    role: "Fullstack",
    level: "Midweight",
    language: ["JavaScript", "Ruby"],
    tools: ["Sass"],
    filters: ["Fullstack", "Midweight", "JavaScript", "Ruby", "Sass"]
  },
  {
    company: "FaceIt",
    tag: [],
    job: "Junior Backend Developer",
    post: "2w ago",
    type: "Full Time",
    location: "UK only",
    role: "Backend",
    level: "Junior",
    language: ["Ruby"],
    tools: ["RoR"],
    filters: ["Backend", "Junior", "Ruby", "RoR"]
  },
  {
    company: "Shortly",
    tag: [],
    job: "Junior Developer",
    post: "2w ago",
    type: "Full Time",
    location: "Worldwide",
    role: "Frontend",
    level: "Junior",
    language: ["HTML", "JavaScript"],
    tools: ["Sass"],
    filters: ["Frontend", "Junior", "HTML", "JavaScript", "Sass"]
  },
  {
    company: "Insure",
    tag: [],
    job: "Junior Frontend Developer",
    post: "2w ago",
    type: "Full Time",
    location: "USA only",
    role: "Frontend",
    level: "Junior",
    language: ["JavaScript"],
    tools: ["Vue", "Sass"],
    filters: ["Frontend", "Junior", "JavaScript", "Vue", "Sass"]
  },
  {
    company: "Eyecam Co.",
    tag: [],
    job: "Full Stack Engineer",
    post: "3w ago",
    type: "Full Time",
    location: "Worldwide",
    role: "Fullstack",
    level: "Midweight",
    language: ["JavaScript", "Python"],
    tools: ["Django"],
    filters: ["Fullstack", "Midweight", "JavaScript", "Python", "Django"]
  },
  {
    company: "The Air Filter Company",
    tag: [],
    job: "Front-end Dev",
    post: "1mo ago",
    type: "Part Time",
    location: "Worldwide",
    role: "Frontend",
    level: "Junior",
    language: ["JavaScript"],
    tools: ["React", "Sass"],
    filters: ["Frontend", "Junior", "JavaScript", "React", "Sass"]
  },
];

export default data;