const data = [
  {
    id: 1,
    company: "Photosnap",
    tag: ["New!", "Featured"],
    job: "Senior Frontend Developer",
    post: "1d ago",
    type: "Full Time",
    location: "USA only",
    role: "Frontend",
    level: "Senior",
    language: ["HTML", "CSS", "JavaScript"],
    tools: [],
    filters: ["Frontend", "Senior", "HTML", "CSS", "JavaScript"]
  },
  {
    id: 2,
    company: "Manage",
    tag: ["New!", "Featured"],
    job: "Fullstack Developer",
    post: "1d ago",
    type: "Part Time",
    location: "Remote",
    role: "Fullstack",
    level: "Midweight",
    language: ["Python"],
    tools: ["React"],
  },
  {
    id: 3,
    company: "Account",
    tag: ["New!"],
    job: "Junior Frontend Developer",
    post: "2d ago",
    type: "Part Time",
    location: "USA only",
    role: "Frontend",
    level: "Junior",
    language: ["JavaScript"],
    tools: ["React", "Sass"],
  },
  {
    id: 4,
    company: "MyHome",
    tag: [],
    job: "Junior Frontend Developer",
    post: "5d ago",
    type: "Contract",
    location: "USA only",
    role: "Frontend",
    level: "Junior",
    language: ["CSS", "JavaScript"],
    tools: [],
  },
  {
    id: 5,
    company: "Loop Studios",
    tag: [],
    job: "Software Engineer",
    post: "1w ago",
    type: "Full Time",
    location: "Worldwide",
    role: "Fullstack",
    level: "Midweight",
    language: ["JavaScript", "Ruby"],
    tools: ["Sass"],
  },
  {
    id: 6,
    company: "FaceIt",
    tag: [],
    job: "Junior Backend Developer",
    post: "2w ago",
    type: "Full Time",
    location: "UK only",
    role: "Backend",
    level: "Junior",
    language: ["Ruby"],
    tools: ["RoR"],
  },
  {
    id: 7,
    company: "Shortly",
    tag: [],
    job: "Junior Developer",
    post: "2w ago",
    type: "Full Time",
    location: "Worldwide",
    role: "Frontend",
    level: "Junior",
    language: ["HTML", "JavaScript"],
    tools: ["Sass"],
  },
  {
    id: 8,
    company: "Insure",
    tag: [],
    job: "Junior Frontend Developer",
    post: "2w ago",
    type: "Full Time",
    location: "USA only",
    role: "Frontend",
    level: "Junior",
    language: ["JavaScript"],
    tools: ["Vue", "Sass"],
  },
  {
    id: 9,
    company: "Eyecam Co.",
    tag: [],
    job: "Full Stack Engineer",
    post: "3w ago",
    type: "Full Time",
    location: "Worldwide",
    role: "Fullstack",
    level: "Midweight",
    language: ["JavaScript", "Python"],
    tools: ["Django"],
  },
  {
    id: 10,
    company: "The Air Filter Company",
    tag: [],
    job: "Front-end Dev",
    post: "1mo ago",
    type: "Part Time",
    location: "Worldwide",
    role: "Frontend",
    level: "Junior",
    language: ["JavaScript"],
    tools: ["React", "Sass"],
  },
];

export default data;